repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        name: End-of-File Fixer
      - id: trailing-whitespace
        name: Trailing Whitespace
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: yarn format
        language: system
        types_or: ["javascript", "json", "markdown", "mdx", "yaml"]
      - id: gitlint
        name: Gitlint
        language: system
        entry: gitlint --commits HEAD --ignore B6
        args: [--staged, --msg-filename]
        stages: [commit-msg]
